name: KeepAlive E5 Dev

on:
  schedule:
    # chạy mỗi ngày 9h sáng UTC (16h VN)
    - cron: "0 2 * * *"
  workflow_dispatch: # cho phép chạy thủ công

jobs:
  run-keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv feedparser flask

      - name: Run KeepAlive Script
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          IMAGE_FOLDER: ${{ secrets.IMAGE_FOLDER }}
          RCLONE_REMOTE: ${{ secrets.RCLONE_REMOTE }}
          RCLONE_CLEAN_FOLDER: ${{ secrets.RCLONE_CLEAN_FOLDER }}
          LOCAL_UPLOAD: ${{ secrets.LOCAL_UPLOAD }}
          REMOTE_UPLOAD: ${{ secrets.REMOTE_UPLOAD }}
          EXTERNAL_EMAILS: ${{ secrets.EXTERNAL_EMAILS }}
        run: |
          python KeepAlive_Combined_Windows.py --app
